### ISSUE TITLE
Exe 0.4.0 bloque au chargement des effets des armes

### ISSUE THREAD

**Issue by RomanBredehoft** [GastonF5/DofusClicker#1]
Lorsque l'on lance l'exe de la version 0.4.0, le chargement se bloque indéfiniment à l'étape "Chargement des effets des armes" 

Cloner le repo, checkout le branche 0.4.0 et run via Godot: 
- plante avec ce message : `Unable to iterate on object of type 'Nil'`
- donne l'erreur :
```
E 0:00:06:0492   API.gd:214 @ check_response_code(): Internal serveur error
  <C++ Source>   core/variant/variant_utility.cpp:1092 @ push_error()
  <Stack Trace>  API.gd:214 @ check_response_code()
                 API.gd:168 @ _on_request_completed()

```
- ne semble download aucune data (le dir 'Data' de l'utilisateur est vide au moment de l'erreur)

**Comment by GastonF5** [comment]
Problème avec une requête vers l'API, correction dans :
https://github.com/GastonF5/DofusClicker/commit/f5bf2bffd6e22a2f938499cf0cab0f4155fa519c
